# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'USC Film' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for USC Film
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Kingfisher', '~> 6.0'
  pod 'youtube-ios-player-helper'
  pod 'SwiftyBeaver'
  target 'USC FilmTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'USC FilmUITests' do
    # Pods for testing
  end
  
end
